#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on March 22 13:23:44 2025
@author: alcantar
example run: python 11_neutral_drift_histograms.py

"""

# activate virtual enviroment before running script
# source activate minibinders

import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from matplotlib.ticker import MaxNLocator

from utils import *

import argparse

def filter_consolidate_variants(df, count_threshold=10):

    consolidated_df = (
        df
        .sort_values(by='read_count', ascending=False)  # Sort by read_count in descending order
        .groupby('aa_sequence', as_index=False)
        .agg({
            'dna_sequence': list, # create a list of all dna sequences which map to an amino acid sequence
            'read_count': 'sum', # sum the read counts
            'dna_mutations': list, # create a list of all dna mutations which map to an amino acid sequence
            'aa_mutations': 'first', # should be the same across all variants, so only take one representative entry
            'number_dna_mutations': list, # create a list of all the number of dna mutations in each dna variant
            'number_aa_mutations': 'first' # should be the same across all variants, so only take one representative entry

        })
    )
    consolidated_df = consolidated_df.copy()[consolidated_df['read_count'] >= count_threshold]
    consolidated_df = consolidated_df.sort_values(by='read_count', ascending=False).reset_index(drop=True)

    return(consolidated_df)

def main():
    # these dataframes were generated by running scripts 01 to 02 on amplicon sequencing data
    # collected post-sorts 8, 15, and 30
    mutation_sort8_df_path = '../data/drift_timepoints/mb376sort8_mutation_analysis.csv'
    mutation_sort15_df_path = '../data/drift_timepoints/mb376sort15_mutation_analysis.csv'
    mutation_sort30_df_path = '../data/drift_timepoints/mb376-sort30_mutation_analysis.csv'


    mutation_sort8_df = pd.read_csv(mutation_sort8_df_path, index_col=0)
    mutation_sort15_df = pd.read_csv(mutation_sort15_df_path, index_col=0)
    mutation_sort30_df = pd.read_csv(mutation_sort30_df_path, index_col=0)

    mutation_sort8_final_df = filter_consolidate_variants(mutation_sort8_df)
    mutation_sort15_final_df = filter_consolidate_variants(mutation_sort15_df)
    mutation_sort30_final_df = filter_consolidate_variants(mutation_sort30_df)
    min_number_variants = np.min([mutation_sort8_final_df.shape[0], mutation_sort15_final_df.shape[0], mutation_sort30_final_df.shape[0]])

    mutation_sort8_rarefied_df = mutation_sort8_final_df.copy().iloc[:min_number_variants,:]
    mutation_sort15_rarefied_df = mutation_sort15_final_df.copy().iloc[:min_number_variants,:]
    mutation_sort30_rarefied_df = mutation_sort30_final_df.copy().iloc[:min_number_variants,:]

    g = sns.histplot(data=mutation_sort8_final_df, x="number_aa_mutations",
                        binwidth=1,stat='probability', color="#DAD9D9",
                         edgecolor='black', linewidth=0.5, alpha=0.5)
    ax = plt.gca()
    g = sns.histplot(data=mutation_sort15_final_df, x="number_aa_mutations",
                        binwidth=1,stat='probability', color="#8E8E8E",
                         edgecolor='black', linewidth=0.5, alpha=0.5)
    ax = plt.gca()
    g = sns.histplot(data=mutation_sort30_final_df, x="number_aa_mutations",
                        binwidth=1,stat='probability', color="#7C256F",
                         edgecolor='black', linewidth=0.5, alpha=0.5, )
    ax = plt.gca()
    g.xaxis.set_major_locator(MaxNLocator(integer=True))

    plt.xlim(right=12)
    plt.xlim(left=0)
    plt.ylim(top=0.7)

    plt.savefig('../figs/neutral_drift_histograms.svg', dpi=400)
    plt.savefig('../figs/neutral_drift_histograms.pdf', dpi=400)
    plt.savefig('../figs/neutral_drift_histograms.png', dpi=400)

    median_sort8 = np.median(mutation_sort8_final_df['number_aa_mutations'].to_list())
    median_sort15 = np.median(mutation_sort15_final_df['number_aa_mutations'].to_list())
    median_sort30= np.median(mutation_sort30_final_df['number_aa_mutations'].to_list())

    print(f'Median mutations after sort 8: {median_sort8}')
    print(f'Median mutations after sort 15: {median_sort15}')
    print(f'Median mutations after sort 30: {median_sort30}')

if __name__ == "__main__":
    main()
