#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on April 3 16:40:16 2026
@author: alcantar
example run: python 19_neutral_drift_mutation_analysis.py
"""

# activate virtual enviroment before running script
# source activate minibinders

import pandas as pd
from utils import *

from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np
from matplotlib.colors import ListedColormap, BoundaryNorm

import ast as ast


def aa_mut_counts(neutral_drift_df, parent_seq):

    '''
    computes how often every possible amino acid mutation occurs

    PARAMETERS
    ------------
    neutral_drift_df: pandas dataframe
        neutral drift mutations dataframe (using the same dataframe used to analyze the library)
    parent_seq: str
        parent amino acid sequence

    RETURNS
    ------------
    aa_mut_df: pandas DataFrame
        dataframe with occurance of every possible amino acid substitution
    '''

    aa_muts_count_dict = dict()

    for _, seq in neutral_drift_df.iterrows():
        aa_mut_temp = seq['aa_mutations']
        aa_mut_list = extract_mutations_from_string(aa_mut_temp) # from utils
        aa_mut_list = [mut.replace(' ','') for mut in aa_mut_list]
        for mut in aa_mut_list:
            try:
                aa_muts_count_dict[mut] = aa_muts_count_dict[mut] + 1
            except KeyError:
                aa_muts_count_dict.update({mut:1})

    aas_alphabet = list('ACDEFGHIKLMNPQRSTVWY')
    df_column = [i for i in range(1, len(parent_seq)+1)]
    aa_mut_df = pd.DataFrame(index=aas_alphabet, columns=df_column)

    # dictionary to map residue number to residue at that position
    res_to_parent_aa_dict = {res:aa for res, aa in zip(aa_mut_df.columns, parent_seq)}

    for mut in aa_muts_count_dict:

        if mut: # this handles the parent sequence case which has no mutations
            orig_res = mut[0]
            res = int(mut[1:-1])
            new_res = mut[-1]

            # fill in df with counts
            aa_mut_df.loc[new_res, res] = aa_muts_count_dict[mut]

    # handle the mutations with no instances
    aa_mut_df = aa_mut_df.fillna(0)

    # convert residue positions to actual parent amino acid sequence
    aa_mut_df = aa_mut_df.rename(columns=res_to_parent_aa_dict)

    return(aa_mut_df)

def plot_aa_mut_occurances(aa_df, num_seqs, occurance_type='frequency',
                           outname='',save=False):

    '''
    creates a heatmap showing how frequently every possible amino acid
    substitution occurs

    PARAMETERS
    ------------
    aa_df: pandas dataframe
    dataframe with occurance of every possible amino acid substitution. should
    be generated by 'aa_mut_counts'
    num_seqs: int
        number of amino acid sequences. This is used to calculate max bounds
        for heatmap colormap
    occurance_type: str
        indicate whether to plot 'frequency' or 'counts'
    outname: str
        output name
    save: boolean
        indicate whether to save plot

    RETURNS
    ------------
    None - just plots the heatmap
    '''

    if occurance_type=='frequency':
        bounds = [0, 1/num_seqs, 0.01, 0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 1]
        aa_df = aa_df.copy()/num_seqs
    elif occurance_type=='counts':
        bounds = [0, 1, 6, 21, 51, 101, 201, 301, 401, num_seqs]
    else:
        print(f'Invalid occurance type: {occurance_type}. Defaulting to frequency')
        bounds = [0, 1/num_seqs, 0.01, 0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 1]
        aa_df = aa_df.copy()/num_seqs

    colors = [
        '#FFFFFF',  # 0 (grey)
        '#223C66',  # dark blue
        '#5D82B0', # blue
        '#9EBCDC', # light blue
        '#E0ECF3', # lightest blue
        '#F4E1D1', #lightest red
        '#BD6958', # light red
        '#94525F', # red
        '#601B25', # dark red
    ]

    cmap = ListedColormap(colors)
    norm = BoundaryNorm(bounds, cmap.N)

    # ---- PLOT ----
    plt.figure(figsize=(20,6))
    sns.heatmap(
        aa_df,
        cmap=cmap,
        norm=norm,
        cbar=True,
        linewidths=0.05,
    linecolor='#AAAAAA')

    if save:
        plt.savefig(f'{outname}.pdf', dpi=400)

def dna_mut_counts(neutral_drift_df, parent_seq_dna):

    '''
    computes how often every possible nucleotide mutation occurs

    PARAMETERS
    ------------
    neutral_drift_df: pandas dataframe
        neutral drift mutations dataframe (using the same dataframe used to analyze the library)
    parent_seq_dna: str
        parent nucleotide sequence

    RETURNS
    ------------
    dna_muts_count_dict: dictionary
        dictionary mapping each unique mutation to how often it occurs
    num_dna_muts: list of int
        list with how many mutations each dna sequences has
    num_dna_seqs: int
        total number of dna sequences
    dna_mut_df: pandas dataframe
        dataframe with number of times each possible nucleotide subsitution occurs
    '''
    dna_muts = []
    num_dna_muts = []
    dna_muts_count_dict = dict()
    num_dna_seqs = 0
    for _, seq in neutral_drift_df.iterrows():
        outer = ast.literal_eval(seq['dna_mutations'])
        mutations = [ast.literal_eval(inner) for inner in outer]
        for mut_list in mutations:
            num_dna_seqs+=1
            for mut in mut_list:
                if mut:
                    dna_muts.append(mut)
                    try:
                        dna_muts_count_dict[mut] = dna_muts_count_dict[mut] + 1
                    except:
                        dna_muts_count_dict[mut] = 1

        for i in seq['number_dna_mutations'][1:-1].split(','):
            num_dna_muts.append(int(i.replace(' ','')))

    dna_alphabet = list('ATCG')
    dna_df_column = [i for i in range(1, len(parent_seq_dna)+1)]
    dna_mut_df = pd.DataFrame(index=dna_alphabet, columns=dna_df_column)
    dna_to_parent_dna_dict = {res:aa for res, aa in zip(dna_mut_df.columns, parent_seq_dna)}
    for mut in dna_muts_count_dict:
        if mut:
            orig_res = mut[0]
            res = int(mut[1:-1])  # ensure integer index
            new_res = mut[-1]

            dna_mut_df.loc[new_res, res] = dna_muts_count_dict[mut]

    dna_mut_df = dna_mut_df.fillna(0)
    dna_mut_df = dna_mut_df.rename(columns=dna_to_parent_dna_dict)

    return(dna_muts_count_dict, num_dna_muts, num_dna_seqs, dna_mut_df)



def plot_dna_mut_occurances(dna_df, num_seqs, n_panels=3, occurance_type='frequency',
                            outname='', save=False):

    '''
    computes how often every possible nucleotide mutation occurs

    PARAMETERS
    ------------
    dna_df: pandas dataframe
        dataframe with number of times each possible nucleotide subsitution occurs
    num_seqs: int
        total number of dna sequences
    n_panels: int
        how many panels to break heatmap into (default 3 to match length of
        amino acid heatmap)
    occurance_type: str
        indicate whether to plot 'frequency' or 'counts'
    outname: str
        output name
    save: boolean
        indicate whether to save plot

    RETURNS
    ------------
    None - just plots the heatmap
    '''
    if occurance_type == 'frequency':
        bounds = [0, 1/num_seqs, 0.01, 0.04, 0.08, 0.2, 0.4, 0.6, 0.8, 1]
        dna_df = dna_df.copy() / num_seqs
    elif occurance_type == 'counts':
        bounds = [0, 1, 51, 251, 501, 1001, 2001, 3001, 4001, num_seqs]
    else:
        print(f'Invalid occurance type: {occurance_type}. Defaulting to frequency')
        bounds = [0, 1/num_seqs, 0.01, 0.04, 0.08, 0.2, 0.4, 0.6, 0.8, 1]
        dna_df = dna_df.copy() / num_seqs

    colors = [
        '#FFFFFF',  # 0 (grey)
        '#223C66',  # dark blue
        '#5D82B0',  # blue
        '#9EBCDC',  # light blue
        '#E0ECF3',  # lightest blue
        '#F4E1D1',  # lightest red
        '#BD6958',  # light red
        '#94525F',  # red
        '#601B25',  # dark red
    ]
    cmap = ListedColormap(colors)
    norm = BoundaryNorm(bounds, cmap.N, clip=True)

    col_splits = np.array_split(np.arange(dna_df.shape[1]), n_panels)
    panels = [dna_df.iloc[:, split] for split in col_splits]

    # Dedicated colorbar column keeps all heatmap panels the same size
    fig, axes = plt.subplots(
        n_panels, 2,
        figsize=(18, 2 * n_panels),
        gridspec_kw={'width_ratios': [1, 0.02], 'wspace': 0.05},
    )

    for i, (panel, ax_row) in enumerate(zip(panels, axes)):
        ax_heatmap, ax_cbar = ax_row
        sns.heatmap(
            panel,
            ax=ax_heatmap,
            cmap=cmap,
            norm=norm,
            cbar=False,
            linewidths=0.05,
            linecolor='#AAAAAA',
        )
        if i < n_panels - 1:
            ax_heatmap.set_xlabel('')
        # Hide unused colorbar axes on all but the middle panel
        ax_cbar.set_visible(False)

    # Draw a single colorbar in the middle colorbar axis
    mid = n_panels // 2
    axes[mid, 1].set_visible(True)
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    fig.colorbar(sm, cax=axes[mid, 1])

    plt.tight_layout()
    if save:
        plt.savefig(f'{outname}.pdf', dpi=400, bbox_inches='tight')


def main():
    neutral_drift_path = '../../minibinders_orthorep_data/minibinders_orthorep_outputs/maa_003/neutral_drift_library/library_scores.csv'
    neutral_drift_df = pd.read_csv(neutral_drift_path, index_col=0)
    parent_seq_aa = 'SLGYYKVTFLPDAHPQAVEILALAFLDNGLEVKEVVTEEGNKYVIAELDEITLEAVKEAIGEIIESVEPVVE'
    aa_mut_df = aa_mut_counts(neutral_drift_df, parent_seq_aa)
    num_aa_seqs = len(neutral_drift_df)
    outdir = '../figs/neutral_drift/'
    make_dir(outdir)
    outname_aa_heatmap = f'{outdir}aa_mut_occurances'
    plot_aa_mut_occurances(aa_mut_df, num_seqs=num_aa_seqs, occurance_type='frequency',
                          outname=outname_aa_heatmap,save=True)


    parent_seq_dna = 'TCTTTAGGTTATTATAAAGTTACTTTTTTACCTGATGCTCATCCTCAAGCTGTTGAAATTTTAGCTTTAGCTTTTTTAGATAATGGTTTAGAAGTTAAAGAAGTTGTTACTGAAGAAGGTAATAAATATGTTATTGCTGAATTAGATGAAATTACTTTAGAAGCTGTTAAAGAAGCTATTGGTGAAATTATTGAATCTGTTGAACCTGTTGTTGAA'
    dna_muts_count_dict, num_dna_muts, num_dna_seqs,dna_mut_df = dna_mut_counts(neutral_drift_df, parent_seq_dna)
    outname_dna_heatmap = f'{outdir}dna_mut_occurances'
    plot_dna_mut_occurances(dna_mut_df, num_dna_seqs, n_panels = 3, occurance_type='frequency',
                               outname=outname_dna_heatmap,save=True)

if __name__ == "__main__":
    main()
